"""One-time script: Generate Juliet's Basket 2 (stability) and Basket 2B (direction-stress) predictions."""
import json, os

BASE = r'C:\Users\ishwor\Music\own-organize\own-market\market-gist\agents\agent-2-juliet\predictions'
STAB = os.path.join(BASE, 'basket2_stability')
STRESS = os.path.join(BASE, 'basket2b_direction_stress')

def save(folder, date, symbol, tf, pred):
    fname = f'{date}__{symbol}__{tf}__prediction.json'
    path = os.path.join(folder, fname)
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(pred, f, indent=2)

def mk(d, a, c, cr, t1, t2, t3, sl, ent, rr, th, ri, wc, q, dc):
    return {
        'direction': d, 'action': a, 'conviction': c, 'conviction_rationale': cr,
        'price_targets': {'target_1':t1,'target_2':t2,'target_3':t3,'stop_loss':sl,'entry_zone':ent,'risk_reward_ratio':rr},
        'thesis': th, 'risks': ri, 'what_would_change_mind': wc,
        'setup_quality': q, 'data_completeness': dc,
        'similar_setup_awareness': {'similar_count':0,'similar_resolved_success_rate_pct':None,'influence_on_conviction':'No similar setups in curated replay mode'}
    }

# ===== BASKET 2 STABILITY (35 predictions) =====
stab_preds = [
# JULY peak season (9)
('2025-07-01','SANIMA','1D','bullish','watch_only',55,'Uptrend at peak season with volume, but 96% of 20d range is extended.',345,355,None,318,[328,334],1.8,'SANIMA in confirmed uptrend entering peak fiscal season. Above all SMAs with 1.71x volume. 3.13% daily and 5.96% weekly show live momentum. But 96.2% of 20d range signals near-term pullback risk.',['Extended at 96% of 20d range','Peak buying may be priced in','No NRB/interbank data'],['Close below SMA20 (316) breaks uptrend','Volume dropping below 1.0x signals exhaustion'],'moderate','partial'),
('2025-07-02','EBL','1D','bullish','watch_only',45,'Improving above SMAs but 0.6x volume not confirming. Peak season tailwind.',670,690,None,630,[640,650],1.5,'EBL improving above both SMAs. Peak season favorable for banking. But 0.6x volume means move lacks conviction. 0.48% 20d return is modest — grinding not thrusting.',['Volume 0.6x not confirming','Only 0.48% 20d return','Missing macro data'],['Volume exceeding 1.2x confirms buying','Close below SMA50 negates improving'],'low_conviction','partial'),
('2025-07-03','NABIL','1D','bullish','watch_only',48,'Improving above SMAs at peak season. Extended at 90.6% but 29% below 52w high.',510,525,None,485,[493,500],1.6,'NABIL improving above both SMAs entering fiscal-year-end. Banking benefits from Ashadh earnings anticipation. 29% gap to 52w high (700) gives room. But 90.6% 20d range and 1.19% 20d return suggest grinding advance.',['Extended at 90.6%','Acceptable liquidity limits execution','Missing macro data'],['Close below SMA20 breaks improving','Banking failing during peak season is red flag'],'moderate','partial'),
('2025-07-06','JBBL','1D','neutral','watch_only',38,'Improving but -1.43% pullback today. Unknown sector, mid-range position.',345,None,None,315,[325,333],1.3,'JBBL improving above SMAs but 1.43% daily decline shows active sellers. 53.5% 20d range is neutral. Peak season helps broadly but unknown sector reduces confidence.',['Unknown sector','Pullback suggests supply','Only acceptable liquidity'],['Decline below SMA20 shifts trend to mixed','Two red sessions with rising volume is distribution'],'low_conviction','partial'),
('2025-07-07','MNBBL','1D','bullish','watch_only',43,'Uptrend with 1.81x volume but -2.09% daily pullback. Unknown sector.',390,405,None,355,[370,378],1.4,'MNBBL in uptrend above all SMAs with 1.81x volume. 4.85% weekly and 3.87% 20d gains solid. But 2.09% daily decline is profit-taking. Unknown sector limits thesis.',['Unknown sector','2.09% daily decline may start pullback','Acceptable liquidity'],['Close below SMA20 breaks uptrend','Volume dropping below 1.0x'],'low_conviction','partial'),
('2025-07-10','MNBBL','1D','bullish','avoid',35,'Extended at 90.8% after 7.85% 20d run. Risk/reward poor for entries.',405,None,None,370,[380,390],0.8,'MNBBL uptrend with 7.85% 20d return is real. But at 90.8% of 20d and 91.5% of 60d range, extremely extended. Pullback risk outweighs near-term upside.',['Extremely extended 91% of ranges','Unknown sector','Mean reversion after 7.85% run'],['Pullback to SMA20 with volume support','Breakout above 52w high (482) on volume'],'no_edge','partial'),
('2025-07-17','UPPER','1D','bullish','watch_only',50,'Strong momentum at peak season with 1.88x volume. 30% below 52w high.',215,225,None,195,[200,206],1.7,'UPPER improving with strong momentum: 3.84% daily, 4.69% weekly above all SMAs. 1.88x volume confirms. 30% below 52w high of 295 gives room. 87.9% 20d range concerning but not extreme.',['Extended at 87.9%','Hydropower can reverse quickly','Missing macro data'],['Close below SMA20 breaks structure','Volume dropping below 1.0x signals exhaustion'],'moderate','partial'),
('2025-07-20','AKPL','1D','neutral','watch_only',40,'Improving above SMAs but -1.48% pullback. Mid-range. No strong conviction.',275,285,None,250,[258,265],1.4,'AKPL improving above both SMAs. 4.46% weekly positive. But 1.48% daily decline and 60.2% 20d range suggest wait-and-see. Volume 1.13x barely confirming.',['Daily pullback suggests supply','Volume barely above 1.0x','Missing macro context'],['Close below SMA50 negates improving','Another 2%+ decline with rising volume'],'low_conviction','partial'),
('2025-07-24','API','1D','bullish','watch_only',55,'Powerful 13.2% 20d surge with 2.27x volume but 99% of 20d range is blowoff.',340,355,None,305,[315,327],1.5,'API surging in confirmed uptrend. 13.2% 20d, 7.25% weekly, 2.27x volume — strongest momentum. But at 99% of 20d range, entering at top of vertical move is poor risk management.',['Extremely extended 99% of 20d','Mean reversion after 13.2% run','Momentum entries at extremes fail often'],['Close below SMA10 signals exhaustion','Volume declining below 1.5x while price stalls'],'moderate','partial'),
# AUGUST post-peak (8)
('2025-08-03','AKPL','1D','bearish','avoid',55,'Sharp 8.64% 5d decline. Post-peak correction. Volume confirms selling.',None,None,None,None,None,None,'AKPL dropped 8.64% in 5 days. Post-fiscal-year-end correction. 36% of 20d range shows pullback is real. Volume 1.28x means selling has participation.',['Post-peak selling may continue','Volume confirms selling','No macro support'],['3 green days with rising volume','Price reclaiming SMA20'],'no_edge','partial'),
('2025-08-04','API','1D','bearish','avoid',52,'Broke below SMA20 after 5.42% weekly decline. Post-peak correction.',None,None,None,None,None,None,'API reversed from July surge, below SMA20 with mixed trend. 5.42% weekly decline and 0.81x volume show momentum evaporated. July blowoff being corrected.',['Post-blowoff correction can be deep','Below SMA20 with declining volume','Further leg down to SMA50 likely'],['Price reclaiming SMA20 with volume above 1.5x','Higher low above SMA50'],'no_edge','partial'),
('2025-08-05','EBL','1D','neutral','avoid',42,'Post-peak correction below SMA20. Flat volume. No direction.',None,None,None,None,None,None,'EBL pulled back from fiscal-year-end high. Below SMA20, above SMA50. 0.56x volume — no conviction either side. 45.5% 20d is neutral. No signal.',['Below SMA20','Volume dried up','Post-peak corrections persist through August'],['Volume expansion above SMA20','SMA50 test with buying response'],'no_edge','partial'),
('2025-08-06','JBBL','1D','bearish','avoid',50,'6.8% weekly decline, below SMA20. Post-peak correction.',None,None,None,None,None,None,'JBBL dropped 6.8% weekly, below SMA20. 34.6% 20d range shows sellers in control. Unknown sector. Avoid until selling stabilizes.',['6.8% weekly decline','Unknown sector','Low volume could mean further downside'],['Price holding SMA50 and reclaiming SMA20','Three higher lows'],'no_edge','partial'),
('2025-08-07','MNBBL','1D','neutral','avoid',40,'Post-peak correction from July run. Below SMA20, low volume.',None,None,None,None,None,None,'MNBBL corrected after July run. Below SMA20 with 0.57x volume. 47.4% 20d neutral. Could stabilize or continue lower. No edge.',['Post-peak may continue','Very low volume','Unknown sector'],['Volume above 1.0x with price above SMA20','Clear support hold'],'no_edge','partial'),
('2025-08-10','NABIL','1D','bearish','avoid',45,'Below SMA20, negative 20d return. Banking weakness post-peak.',None,None,None,None,None,None,'NABIL post-peak weakness below SMA20 with negative 20d return. 0.54x volume. 26.3% of 20d range. August banking typically sees quiet selling.',['Below SMA20 with negative 20d return','Very low volume','August weak for banking'],['NRB policy supporting growth','Price reclaiming SMA20 with sector strength'],'no_edge','partial'),
('2025-08-11','SANIMA','1D','neutral','avoid',38,'Below SMA20, volume collapsed to 0.48x. No buyer interest.',None,None,None,None,None,None,'SANIMA below SMA20 after July peak. 0.48x volume among lowest. 45.9% 20d neutral but no buying. Wait for capitulation or volume-confirmed recovery.',['Volume collapsed','Below SMA20','Post-peak correction may continue'],['Volume above 1.2x with SMA20 reclaim','Banking sector catalyst'],'no_edge','partial'),
('2025-08-12','UPPER','1D','bearish','avoid',60,'Below both SMAs, near 52w low. 6.5% of 20d range. Broken.',None,None,None,None,None,None,'UPPER weakest in basket. Below both SMAs, 6.5% of 20d range. Close 196.51 only 2.3% above 52w low 192. Broken structure.',['Near 52w low','Below both SMAs','Persistent hydropower weakness'],['Price reclaiming both SMAs with volume','Capitulation reversal at 52w low'],'no_edge','partial'),
# OCTOBER dividend season (9)
('2025-10-01','AKPL','1D','neutral','watch_only',38,'Improving above SMA20 but below SMA50. 0.48x volume, no conviction.',268,275,None,248,[255,260],1.2,'AKPL improving above SMA20 but 0.48x volume and 0.73% 20d return are anemic. Extended at 86.9% without conviction. Below SMA50.',['Very weak volume','Extended without conviction','Below SMA50'],['Volume above 1.5x clearing SMA50','Close below SMA20 negates improving'],'low_conviction','partial'),
('2025-10-02','API','1D','neutral','watch_only',38,'Improving above SMA20 but below SMA50. Minimal returns, weak volume.',300,310,None,278,[285,292],1.3,'API improving technically but thin: 0.54% 20d, 0.58x volume. Above SMA20 but below SMA50. Dividend season may support but no urgency.',['Below SMA50','Volume well below 1.0x','Minimal returns'],['Volume above 1.2x breaking SMA50','Close below SMA20 ends improving'],'low_conviction','partial'),
('2025-10-02','UPPER','1D','neutral','watch_only',38,'Improving above SMA20, below SMA50. Weak volume.',195,200,None,178,[184,189],1.3,'UPPER recovering from August. Above SMA20 but below SMA50. 0.56x volume — disinterest. Mild dividend season support.',['Below SMA50','Weak volume','Hydropower lagging since August'],['Break above SMA50 with volume','Sector hydropower catalyst'],'low_conviction','partial'),
('2025-10-05','NABIL','1D','bullish','watch_only',45,'Above both SMAs, improving. Extended at 98.2% but dividend season supports.',535,545,None,510,[520,527],1.4,'NABIL strongest October position — above both SMAs. Dividend season supports banking. But 98.2% 20d range extremely extended and 0.66x volume lacks energy.',['Extremely extended 98.2%','Volume only 0.66x','Low-volume extended environments fail'],['Pullback to SMA20 with volume support','Volume above 1.2x maintaining structure'],'moderate','partial'),
('2025-10-06','EBL','1D','neutral','watch_only',38,'Improving above SMA20 but below SMA50. Extended at 94.1%. 0.4x volume.',730,740,None,700,[710,720],1.1,'EBL improving but empty: 0% returns, 0.4x volume. Extended without energy. Below SMA50.',['0.4x volume lowest in basket','Extended no momentum','Below SMA50'],['Volume above 1.0 breaking SMA50','Close below SMA20 invalidates'],'low_conviction','partial'),
('2025-10-07','JBBL','1D','bearish','avoid',50,'Below both SMAs, weak liquidity. 2.45% daily decline, active selling.',None,None,None,None,None,None,'JBBL weak: below both SMAs, negative returns, weak liquidity. 2.45% daily shows selling. 20.3% of 60d range. Unknown sector.',['Below both SMAs with selling','Weak liquidity','Unknown sector'],['Price reclaiming both SMAs with improved liquidity','Three higher lows on rising volume'],'no_edge','partial'),
('2025-10-08','MNBBL','1D','bearish','avoid',50,'Below both SMAs, -3.19% daily on 1.09x volume. Distribution.',None,None,None,None,None,None,'MNBBL actively sold: 3.19% daily and 3.74% weekly on 1.09x volume. Below both SMAs at 34.9% of 60d range.',['Active selling with volume','Below both SMAs','Unknown sector'],['Selling exhaustion above support','Price reclaiming SMA20 with declining dip volume'],'no_edge','partial'),
('2025-10-09','SANIMA','1D','bearish','avoid',60,'Downtrend, below both SMAs, -10.72% 20d. Daily bounce is relief not reversal.',None,None,None,None,None,None,'SANIMA confirmed downtrend: -10.72% 20d, -2.69% 5d. 1.88% daily bounce is dead-cat. Banking stock in downtrend during dividend season is very negative.',['Confirmed downtrend','-10.72% severe for banking','Bounce in downtrend is not reversal'],['Three strong green days reclaiming SMA20','Banking sector reversal with NRB catalyst'],'no_edge','partial'),
('2025-10-12','AKPL','1D','bearish','avoid',55,'Downtrend, below both SMAs, -6.27% weekly. Distribution confirmed.',None,None,None,None,None,None,'AKPL shifted to downtrend. 6.27% weekly with 1.02x volume — sellers engaged. October improving phase was false start.',['Downtrend with selling volume','Below both SMAs','6.27% weekly aggressive'],['Stabilizing above 52w support (216)','Reclaiming SMA20'],'no_edge','partial'),
# NOVEMBER quiet season (9)
('2025-11-02','JBBL','1D','neutral','watch_only',38,'Above SMAs with 8.14% weekly rally but weak liquidity. Suspicious spike.',340,350,None,315,[325,331],1.3,'JBBL 8.14% weekly rally but flat 20d and weak liquidity suggest low-conviction bounce. Above SMAs with 1.24x volume technically positive but weak liquidity means reversals likely.',['Weak liquidity — thin moves unreliable','Spike not supported by 20d','Unknown sector'],['Sustained above-SMA with improving liquidity','Close below SMA50 negates recovery'],'low_conviction','partial'),
('2025-11-03','MNBBL','1D','bearish','avoid',60,'Downtrend, -19.08% 20d. Near 52w low. Broken.',None,None,None,None,None,None,'MNBBL collapsed 19.08% in 20 days. Below both SMAs, 8.7% of 20d range. Near 52w low 349. 0.45x volume — no participants.',['19.08% decline','Near 52w low','No participants'],['Volume spike capitulation with SMA20 recovery','Fundamental catalyst'],'no_edge','partial'),
('2025-11-04','SANIMA','1D','neutral','avoid',42,'Mixed, below SMA50, negative 20d. Recovery faltering.',None,None,None,None,None,None,'SANIMA mixed: above SMA20 but below SMA50 with -2.76% 20d return. -1.25% daily suggests recovery stalling. Banking should be stronger.',['Below SMA50','Negative 20d return','Recovery stalling'],['Price clearing SMA50 with volume','Banking dividend catalyst'],'low_conviction','partial'),
('2025-11-05','AKPL','1D','neutral','watch_only',40,'Improving above SMA20, below SMA50. 1.58x volume best signal.',258,265,None,237,[245,250],1.4,'AKPL improving after October selloff. 1.58x volume strongest in November. Above SMA20 with 3.96% weekly. Below SMA50 — broader recovery unconfirmed.',['Below SMA50','Only 0.77% 20d return','Quiet season'],['Break above SMA50 confirms recovery','Close below SMA20 negates improving'],'low_conviction','partial'),
('2025-11-06','API','1D','bearish','avoid',45,'Below SMA50, -2.11% daily on 1.68x volume. Selling has conviction.',None,None,None,None,None,None,'API mixed with negatives dominating. 2.11% daily and 2.07% weekly declines on 1.68x volume. Below SMA50 with negative 20d return.',['Selling on elevated volume','Below SMA50','Declining momentum'],['Volume-confirmed bounce above both SMAs','Hydropower catalyst'],'no_edge','partial'),
('2025-11-16','EBL','1D','neutral','watch_only',35,'Flat: 0.16% over 20 days. Improving label but nothing moving.',640,650,None,618,[625,632],1.1,'EBL flattest case: 0.16% across all timeframes. Improving above SMA20 but meaningless with zero movement. Below SMA50, 1.0x volume. Sleeping.',['Completely flat','Below SMA50','No catalyst'],['Break above SMA50 with volume','Banking catalyst'],'no_edge','partial'),
('2025-11-23','UPPER','1D','neutral','watch_only',40,'Improving above SMA20, below SMA50. Mild 2.87% weekly gain.',185,190,None,170,[175,179],1.3,'UPPER improving above SMA20 with mild momentum. 1.1x volume barely confirms. Below SMA50. Quiet season limits catalysts.',['Below SMA50','Volume barely confirming','Quiet season'],['Break above SMA50 with rising volume','Close below SMA20 negates improving'],'low_conviction','partial'),
('2025-11-24','API','1D','bullish','watch_only',48,'Above both SMAs with 5.37% 20d return. Best November structure.',295,305,None,272,[280,287],1.5,'API best November structure: above both SMAs, 5.37% 20d. 60.9% 20d has room. 0.86x volume is weakness but structural signal is real.',['Volume below 1.0x','Quiet season limits follow-through','Resistance at 335'],['Close below SMA50 breaks structure','Volume drying at resistance'],'moderate','partial'),
('2025-11-25','NABIL','1D','neutral','watch_only',38,'Improving above SMA20, below SMA50. Very flat. No conviction.',518,525,None,498,[505,511],1.1,'NABIL improving but asleep: -0.49% daily, 0.67% weekly, 0.29% 20d. Below SMA50, 0.89x volume. Banking in quiet season, no catalyst.',['Below SMA50','Volume below 1.0x','Extremely flat'],['Break above SMA50 with volume','Banking catalyst'],'low_conviction','partial'),
]

# ===== BASKET 2B DIRECTION STRESS (29 predictions) =====
stress_preds = [
# JULY (13 cases — all non-avoid)
('2025-07-01','SANIMA','1D','bullish','watch_only',55,'Uptrend at peak season with volume but 96% of 20d range is extended.',345,355,None,318,[328,334],1.8,'SANIMA in confirmed uptrend entering peak fiscal season. Above all SMAs with 1.71x volume. Strong momentum but 96.2% of 20d range signals pullback risk.',['Extended at 96% of 20d range','Peak buying may be priced in','No NRB/interbank data'],['Close below SMA20 breaks uptrend','Volume dropping below 1.0x signals exhaustion'],'moderate','partial'),
('2025-07-02','EBL','1D','bullish','watch_only',45,'Improving above SMAs but 0.6x volume not confirming. Peak season helps.',670,690,None,630,[640,650],1.5,'EBL improving above both SMAs in peak season. But 0.6x volume means low conviction. 0.48% 20d return is grinding not breakout.',['Volume 0.6x not confirming','Only 0.48% 20d return','Missing macro data'],['Volume exceeding 1.2x confirms buying','Close below SMA50 negates improving'],'low_conviction','partial'),
('2025-07-03','NABIL','1D','bullish','watch_only',48,'Improving above SMAs at peak season. Extended near-term but room to 52w high.',510,525,None,485,[493,500],1.6,'NABIL improving above both SMAs. Ashadh earnings anticipation. 29% gap to 52w high gives room. 90.6% 20d range and modest 20d return suggest grinding advance.',['Extended at 90.6%','Acceptable liquidity','Missing macro data'],['Close below SMA20','Banking failing during peak season'],'moderate','partial'),
('2025-07-06','EBL','1D','bullish','watch_only',48,'Improving above both SMAs at 91.3% of 20d range. 1.08x volume provides mild confirmation.',670,690,None,640,[650,660],1.5,'EBL continuing its improving structure with price above both SMAs. 2.44% weekly gain with 1.08x volume ratio provides better confirmation than 4 days prior. Peak season and 76.9% of 60d range shows room to run. But 91.3% 20d position is near-term extended.',['Extended at 91.3% of 20d range','Only 2.54% 20d return is modest','Missing macro data on NRB policy'],['Close below SMA20 breaks improving structure','Volume declining to below 0.8x while price stalls'],'moderate','partial'),
('2025-07-07','NABIL','1D','bullish','watch_only',43,'Improving above SMAs but -0.76% pullback today. Modest 1.25% 20d return.',510,525,None,485,[490,498],1.5,'NABIL improving above both SMAs but the 0.76% daily decline shows near-term weakness. The 62.3% 20d range is more balanced than last week. 1.21x volume is mildly confirming. Peak season provides tailwind but conviction on direction is moderate.',['Daily pullback shows active sellers','Only 1.07% weekly return is tepid','Missing macro context'],['Close below SMA20 shifts trend label from improving','Broader banking sector failing to rally during peak season'],'low_conviction','partial'),
('2025-07-09','SANIMA','1D','bullish','watch_only',52,'Uptrend confirmed, 7.66% 20d return with 1.82x volume. Extended at 93.1% but strong.',350,360,None,325,[335,342],1.8,'SANIMA continues its uptrend with exceptional metrics: 7.66% 20d return and 1.82x volume ratio. The trend is real and confirmed. However, at 93.1% of 20d and 94.9% of 60d range, the stock is extended in both timeframes. Peak season supports but late entry risk is elevated.',['Extended at 93-95% of both ranges','Late entry after 7.66% 20d run','2.03% daily may be acceleration before exhaustion'],['Close below SMA20 breaks uptrend','Volume spike followed by reversal day (bearish engulfing)'],'moderate','partial'),
('2025-07-10','MNBBL','1D','bullish','watch_only',43,'Uptrend with 7.85% 20d return. Extended at 90.8% but momentum real.',405,420,None,375,[385,390],1.5,'MNBBL in uptrend above all SMAs with strong 20d performance. 1.32x volume mildly confirms. But at 90.8% of 20d and 91.5% of 60d range, extremely extended. Unknown sector limits conviction.',['Extremely extended both timeframes','Unknown sector','Mean reversion risk after 7.85% run'],['Close below SMA20','Volume declining while price stalls'],'low_conviction','partial'),
('2025-07-16','MNBBL','1D','bullish','watch_only',42,'Uptrend with 13.12% 20d gain and 1.73x volume. But 96.3% extended — very late in the move.',420,440,None,390,[400,406],1.3,'MNBBL has accelerated: 13.12% 20d return, 5.88% weekly, 3.25% daily. Volume at 1.73x confirms. But at 96.3% of 20d and 96.5% of 60d range, this is extremely late-stage. The acceleration itself may be the final push before exhaustion.',['Extremely late-stage extension 96%+','13.12% in 20 days is aggressive','Unknown sector — cannot assess fundamental support'],['Any daily close below previous day low with volume expansion','Volume ratio dropping below 1.0 while price range narrows'],'low_conviction','partial'),
('2025-07-17','API','1D','bullish','watch_only',48,'Improving above both SMAs with 1.29x volume. 83.6% 20d range — room for continuation.',315,325,None,290,[298,305],1.6,'API improving with price above both SMAs. 2.92% daily and 3.66% weekly show momentum building. 1.29x volume confirms buyers. At 83.6% of 20d range there is room before becoming extremely extended. Peak season and still 22% below 52w high.',['Hydropower sector can be volatile','Only 2.15% 20d return — momentum is early stage','Missing macro context'],['Close below SMA20 breaks improving structure','Hydropower sector rolling over broadly'],'moderate','partial'),
('2025-07-20','AKPL','1D','neutral','watch_only',40,'Improving above SMAs but -1.48% pullback. Mid-range. No strong conviction.',275,285,None,250,[258,265],1.4,'AKPL improving above both SMAs. 4.46% weekly positive. But 1.48% decline and 60.2% 20d suggest wait-and-see. Volume 1.13x barely confirming.',['Daily pullback suggests supply','Volume barely above 1.0x','Missing macro context'],['Close below SMA50 negates improving','Another 2%+ decline with rising volume'],'low_conviction','partial'),
('2025-07-21','AKPL','1D','neutral','watch_only',40,'Improving above SMAs, flat day. Same mid-range setup as yesterday.',275,285,None,250,[258,265],1.4,'AKPL nearly unchanged from yesterday: -0.05% daily but still 4.4% weekly. Above both SMAs with 1.25x volume. The 59.6% 20d position gives room. But the two consecutive days of weakness after a strong week suggest momentum fading.',['Two soft days may signal momentum fading','Volume at 1.25x is not strong enough for directional conviction','Missing macro data'],['Close below SMA50 negates improving','Clear break above recent highs with volume expanding'],'low_conviction','partial'),
('2025-07-22','UPPER','1D','bullish','watch_only',52,'Improving with 6.13% weekly and 2.38x volume surge. Peak season. 80.2% 20d has room.',220,230,None,198,[205,210],1.8,'UPPER showing strong momentum: 2.05% daily, 6.13% weekly, 8.06% 20d with exceptional 2.38x volume. Above both SMAs. The volume surge is the strongest signal. Still 29% below 52w high. Peak season timing. 80.2% 20d is elevated but not extreme.',['Hydropower can reverse quickly','2.38x volume may be climactic rather than confirming','Missing macro data'],['Close below SMA20 breaks structure','Volume declining to below 1.0x while price consolidates'],'moderate','partial'),
('2025-07-24','API','1D','bullish','watch_only',55,'Powerful 13.2% 20d surge with 2.27x volume. But 99% extended — blowoff risk.',340,355,None,305,[315,327],1.5,'API surging: 13.2% 20d, 7.25% weekly, 2.27x volume — strongest in basket. But 99% of 20d range is vertical. Peak season supports but entering at top of blowoff is poor risk management.',['Extremely extended 99%','Mean reversion after 13.2% run','Blowoff entries have high failure rates'],['Close below SMA10 signals exhaustion','Volume declining below 1.5x while price stalls'],'moderate','partial'),
# OCTOBER (10 cases — all non-avoid)
('2025-10-01','AKPL','1D','neutral','watch_only',38,'Improving above SMA20 but below SMA50. 0.48x volume is very weak.',268,275,None,248,[255,260],1.2,'AKPL technically improving but substance is thin. 0.48x volume and 0.73% 20d return. Extended at 86.9% without conviction. Below SMA50.',['Very weak volume','Extended without conviction','Below SMA50'],['Volume above 1.5x clearing SMA50','Close below SMA20'],'low_conviction','partial'),
('2025-10-01','NABIL','1D','neutral','watch_only',40,'Above both SMAs, improving. Extended at 98.2% with 0.65x volume. Low energy.',535,545,None,510,[520,527],1.4,'NABIL above both SMAs in dividend season. But 98.2% 20d extension with 0.65x volume is extremely stretched on no energy. The position is technically strong but the lack of participation makes it fragile.',['Extremely extended 98.2%','Volume 0.65x — very low energy','Extended with no participation is fragile'],['Pullback to SMA20 with volume support makes better entry','Volume expanding above 1.2x'],'low_conviction','partial'),
('2025-10-02','AKPL','1D','neutral','watch_only',38,'Same setup as yesterday. Improving but anemic volume and below SMA50.',268,275,None,248,[255,260],1.2,'AKPL unchanged from yesterday. Improving above SMA20, below SMA50. Volume 0.49x still very weak. 1.71% 20d return is marginally better but conviction remains low.',['Weak volume persists','Below SMA50','Minimal momentum'],['Volume above 1.5x clearing SMA50','Close below SMA20'],'low_conviction','partial'),
('2025-10-02','NABIL','1D','neutral','watch_only',40,'Still extremely extended above both SMAs with low volume.',535,545,None,510,[520,527],1.4,'NABIL still at 98.2% of 20d range above both SMAs. Volume 0.67x marginally better than yesterday. Dividend season provides floor but no catalyst for further advance.',['Still extended 98.2%','Volume below 1.0x','Risk/reward poor for new entries at extremes'],['Pullback to SMA20 area','Volume expanding with directional move'],'low_conviction','partial'),
('2025-10-05','API','1D','neutral','watch_only',36,'Improving above SMA20 but below SMA50. Zero recent movement. 0.58x volume.',300,310,None,278,[285,292],1.3,'API improving technically but dead: 0% daily, 0% weekly, 0.85% 20d. Above SMA20 but below SMA50 with very low volume. No one is trading this. Dividend season provides background support but no active catalyst.',['Zero momentum','Below SMA50','Very weak volume 0.58x'],['Volume expansion above 1.0x with break above SMA50','Close below SMA20'],'low_conviction','partial'),
('2025-10-05','UPPER','1D','neutral','watch_only',36,'Improving above SMA20, below SMA50. Zero movement, weak volume.',195,200,None,178,[184,189],1.3,'UPPER same pattern as API: improving label but zero daily/weekly returns. 0.57x volume. Above SMA20 below SMA50. Acceptable liquidity. No catalyst.',['Zero momentum','Below SMA50','Weak volume'],['Break above SMA50 with volume','Sector catalyst'],'low_conviction','partial'),
('2025-10-06','API','1D','neutral','watch_only',36,'Same dead setup as yesterday. Improving but zero energy.',300,310,None,278,[285,292],1.3,'API continues with zero daily/weekly movement. 0.59x volume barely changed. Above SMA20 below SMA50. 1.64% 20d is marginally positive. Nothing has changed.',['Continued zero momentum','Below SMA50','Market disengaged'],['Volume expansion with directional break','Close below SMA20'],'low_conviction','partial'),
('2025-10-06','UPPER','1D','neutral','watch_only',38,'Improving, zero movement but 3.14% 20d return is slightly better than peers.',195,200,None,178,[184,189],1.3,'UPPER showing slightly more life than API: 3.14% 20d return. Still zero daily/weekly. Above SMA20 below SMA50 with 0.57x volume. The 20d return suggests underlying drift upward even if daily action is flat.',['Still zero daily momentum','Below SMA50','Weak volume'],['Break above SMA50 with volume','Sector catalyst'],'low_conviction','partial'),
('2025-10-07','EBL','1D','neutral','watch_only',38,'Improving above SMA20, below SMA50. Extended at 94.1% with 0.58x volume.',730,740,None,700,[710,720],1.1,'EBL improving but extended at 94.1% with no energy. 0.58x volume. Below SMA50. 1.19% 20d is minimal. The extension makes risk/reward poor for entries.',['Extended at 94.1%','Very low volume 0.58x','Below SMA50'],['Volume expansion breaking SMA50','Close below SMA20'],'low_conviction','partial'),
('2025-10-09','EBL','1D','neutral','watch_only',40,'Pulled back from extension to 74.2% of 20d range. 1.15x volume on the dip is interesting.',725,740,None,700,[710,720],1.2,'EBL pulled back from its extended position: now at 74.2% of 20d range vs 94.1% two days ago. The 1.15x volume ratio on this pullback is the first meaningful volume signal in weeks. 0.9% daily gain after -0.42% weekly suggests some buying interest at this level. Still below SMA50.',['Below SMA50','Only 0.76% 20d return','Could be dead-cat in broader weakness'],['Break above SMA50 with rising volume','Close below SMA20 negates the setup'],'low_conviction','partial'),
# NOVEMBER (6 cases — all non-avoid)
('2025-11-05','AKPL','1D','neutral','watch_only',40,'Improving above SMA20, below SMA50. 1.58x volume is best signal.',258,265,None,237,[245,250],1.4,'AKPL improving after October selloff. 1.58x volume strongest in November. Above SMA20 with 3.96% weekly. Below SMA50 — recovery unconfirmed.',['Below SMA50','Only 0.77% 20d return','Quiet season'],['Break above SMA50 confirms recovery','Close below SMA20 negates improving'],'low_conviction','partial'),
('2025-11-16','EBL','1D','neutral','watch_only',35,'Flat: 0.16% over 20 days. Improving label but nothing happening.',640,650,None,618,[625,632],1.1,'EBL flattest case: 0.16% across all timeframes. Improving above SMA20 but meaningless with zero movement. Below SMA50.',['Completely flat','Below SMA50','No catalyst'],['Break above SMA50 with volume','Banking catalyst'],'no_edge','partial'),
('2025-11-23','UPPER','1D','neutral','watch_only',40,'Improving above SMA20, below SMA50. Mild gains, quiet season.',185,190,None,170,[175,179],1.3,'UPPER improving with mild positive momentum. 1.1x volume barely confirms. Below SMA50. Quiet season.',['Below SMA50','Volume barely confirming','Quiet season'],['Break above SMA50','Close below SMA20'],'low_conviction','partial'),
('2025-11-24','API','1D','bullish','watch_only',48,'Above both SMAs with 5.37% 20d return. Best November structure.',295,305,None,272,[280,287],1.5,'API best November structure: above both SMAs, 5.37% 20d. 0.86x volume is weakness but real structural signal.',['Volume below 1.0x','Quiet season limits follow-through','Resistance at 335'],['Close below SMA50','Volume drying at resistance'],'moderate','partial'),
('2025-11-25','NABIL','1D','neutral','watch_only',38,'Improving above SMA20, below SMA50. Very flat. No conviction.',518,525,None,498,[505,511],1.1,'NABIL improving but asleep: 0.29% 20d. Below SMA50, 0.89x volume. Banking in quiet season.',['Below SMA50','Volume below 1.0x','Extremely flat'],['Break above SMA50 with volume','Banking catalyst'],'low_conviction','partial'),
('2025-11-26','UPPER','1D','bullish','watch_only',42,'Improving above both SMAs with 3.94% weekly. Volume 1.28x mildly confirms.',190,198,None,173,[178,182],1.5,'UPPER shows better structure than 3 days ago: above both SMAs now (not just SMA20), 3.94% weekly with 1.28x volume. 69.3% 20d range has room. Quiet season limits but the dual-SMA positioning is a real improvement.',['Quiet season limits upside','Hydropower sector has been inconsistent','Only 1.39% 20d return is modest'],['Close below SMA50 would break the constructive setup','Volume drying up below 0.8x'],'low_conviction','partial'),
]

# Write all stability predictions
count_s = 0
for p in stab_preds:
    pred = mk(p[3],p[4],p[5],p[6],p[7],p[8],p[9],p[10],p[11],p[12],p[13],p[14],p[15],p[16],p[17])
    save(STAB, p[0], p[1], p[2], pred)
    count_s += 1

# Write all direction-stress predictions
count_d = 0
for p in stress_preds:
    pred = mk(p[3],p[4],p[5],p[6],p[7],p[8],p[9],p[10],p[11],p[12],p[13],p[14],p[15],p[16],p[17])
    save(STRESS, p[0], p[1], p[2], pred)
    count_d += 1

print(f"Stability basket: {count_s} predictions written")
print(f"Direction-stress basket: {count_d} predictions written")
print(f"Total: {count_s + count_d}")
